### ISSUE TITLE
Better Blocker is dead.

### ISSUE THREAD

**Issue by vecna13** [notriddle/shouldiblockads.com#7]
Better is dead, as seen from [its homepage](https://better.fyi/) and [this blog post](https://ar.al/2021/12/16/saying-goodbye-to-an-old-friend/). It should be removed from the list of recommendations. Small Technology Foundation is recommending 1Blocker instead, and 1Blocker is offering 3 months free to anyone switching from Better.

**Comment by notriddle** [comment]
Thanks for the info. 👍
